
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 10 16:56:26 EDT 2012
//----------------------------------------------------

package featParser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INPUT = 16;
  public static final int TYPES = 3;
  public static final int IDENT = 22;
  public static final int EQL = 19;
  public static final int PLUS = 17;
  public static final int DOLLAR = 10;
  public static final int SEMI = 11;
  public static final int STAR = 9;
  public static final int RSB = 15;
  public static final int FEATURES = 4;
  public static final int DOUB = 20;
  public static final int RELATIONS = 5;
  public static final int LB = 12;
  public static final int WEIGHTS = 6;
  public static final int EXAMPLE = 18;
  public static final int RB = 13;
  public static final int COMMA = 8;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ARROW = 2;
  public static final int ASSIGN = 7;
  public static final int LSB = 14;
}

