/* The following code was generated by JFlex 1.4_pre3 on 10/10/12 4:56 PM */

package dataParser;

import java_cup.runtime.SymbolFactory;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4_pre3
 * on 10/10/12 4:56 PM from the specification file
 * <tt>file:/C:/cygwin/home/ves/code/erma/jflex/DataFileScanner.jflex</tt>
 */
class DataFileScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int YY_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 34,  4,  0, 19,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    34,  0,  0,  0,  0,  0,  0,  0,  9, 10,  6,  8, 11, 15, 16,  5, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 25,  7,  0, 14, 33,  0, 
     0,  2,  2,  2,  2, 18,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 12,  0, 13,  0,  2, 
     0, 21,  2,  2,  2, 17, 26,  2,  2, 31,  2,  2, 24, 22, 32,  2, 
    23,  2, 29, 30, 27, 28,  2,  2, 20,  2,  2,  0,  0,  0,  0,  0
  };


  /** 
   * Translates a state to a row index in the transition table (packed version)
   */
  final private static String yy_rowMap_packed = 
    "\0\0\0\43\0\106\0\151\0\214\0\43\0\257\0\43\0\43\0\43"+
    "\0\43\0\43\0\43\0\43\0\43\0\322\0\365\0\u0118\0\u013b\0\u015e"+
    "\0\u0181\0\u01a4\0\u01c7\0\214\0\u01ea\0\u020d\0\43\0\u0230\0\u0118\0\u0118"+
    "\0\u0253\0\u0276\0\151\0\u0299\0\u02bc\0\43\0\u02df\0\u0302\0\u0325\0\u0348"+
    "\0\u036b\0\u02df\0\u038e\0\u03b1\0\u03d4\0\u03f7\0\u041a\0\u043d\0\u0460\0\u0483"+
    "\0\43\0\u04a6\0\43";

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int [] yy_rowMap = yy_unpack_rowMap(yy_rowMap_packed);


  /** 
   * Unpacks the compressed row translation table.
   *
   * @param packed   the packed row translation table
   * @return         the unpacked row translation table
   */
  private static int [] yy_unpack_rowMap(String packed) {
    int [] map = new int[106];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 106) {
      int high = ((int) packed.charAt(i++)) << 16;
      map[j++] = high | packed.charAt(i++);
    }
    return map;
  }
  /** 
   * The packed transition table of the DFA (part 0)
   */
  private static final String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\4\1\6\5\4\1\2\1\24\4\4"+
    "\1\25\1\4\1\2\1\5\44\0\1\3\16\0\1\26"+
    "\2\27\21\0\2\4\16\0\2\4\1\0\5\4\1\0"+
    "\7\4\5\0\1\30\36\0\1\30\5\0\1\31\1\32"+
    "\75\0\1\33\2\0\1\34\16\0\1\35\23\0\1\36"+
    "\42\0\2\4\16\0\2\4\1\0\1\37\4\4\1\0"+
    "\7\4\3\0\2\4\16\0\1\40\1\4\1\0\5\4"+
    "\1\0\7\4\3\0\2\4\16\0\2\4\1\0\5\4"+
    "\1\0\6\4\1\41\3\0\1\42\42\0\1\36\15\0"+
    "\1\35\23\0\3\31\1\43\1\44\36\31\6\45\1\46"+
    "\34\45\1\0\1\34\16\0\1\26\2\27\21\0\2\4"+
    "\16\0\2\4\1\0\1\4\1\47\3\4\1\0\7\4"+
    "\3\0\2\4\16\0\2\4\1\0\1\4\1\50\3\4"+
    "\1\0\7\4\3\0\1\42\17\0\2\27\24\0\1\44"+
    "\36\0\6\45\1\51\41\45\1\52\1\51\34\45\1\0"+
    "\2\4\16\0\2\4\1\0\2\4\1\53\2\4\1\0"+
    "\7\4\3\0\2\4\16\0\2\4\1\0\5\4\1\0"+
    "\1\4\1\54\5\4\2\0\5\45\1\44\1\51\34\45"+
    "\1\0\2\4\16\0\2\4\1\0\3\4\1\55\1\4"+
    "\1\0\7\4\3\0\2\4\16\0\2\4\1\0\5\4"+
    "\1\0\2\4\1\56\4\4\3\0\2\4\16\0\2\4"+
    "\1\0\4\4\1\57\1\0\7\4\3\0\2\4\16\0"+
    "\2\4\1\0\5\4\1\0\3\4\1\60\3\4\3\0"+
    "\2\4\16\0\1\61\1\4\1\0\5\4\1\0\7\4"+
    "\3\0\2\4\16\0\1\62\1\4\1\0\5\4\1\0"+
    "\7\4\3\0\2\4\16\0\2\4\1\0\5\4\1\63"+
    "\7\4\3\0\2\4\16\0\2\4\1\0\5\4\1\0"+
    "\4\4\1\64\2\4\3\0\2\4\16\0\2\4\1\0"+
    "\5\4\1\65\7\4\2\0";

  /** 
   * The transition table of the DFA
   */
  private static final int yytrans [] = yy_unpack();


  /* error codes */
  private static final int YY_UNKNOWN_ERROR = 0;
  private static final int YY_ILLEGAL_STATE = 1;
  private static final int YY_NO_MATCH = 2;
  private static final int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  private static final String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final byte YY_ATTRIBUTE[] = {
     0,  9,  1,  1,  1,  9,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1, 
     1,  1,  1,  1,  1,  0,  0,  1,  0,  0,  9,  1,  0,  1,  1,  1, 
     1,  1,  1,  9,  0,  0,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  9,  1,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	public DataFileScanner(java.io.InputStream r, SymbolFactory sf){
		this(r);
		this.sf=sf;
	}
	private SymbolFactory sf;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  DataFileScanner(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  DataFileScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1225];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 9: 
          {  return sf.newSymbol("Plus",sym.PLUS);  }
        case 54: break;
        case 7: 
          {  return sf.newSymbol("Star",sym.STAR);  }
        case 55: break;
        case 4: 
        case 5: 
          {  /* ignore white space. */  }
        case 56: break;
        case 11: 
          {  return sf.newSymbol("Right Bracket",sym.RB);  }
        case 57: break;
        case 23: 
          { 
    
 }
        case 58: break;
        case 52: 
          {  return sf.newSymbol("Features", sym.FEATURES);  }
        case 59: break;
        case 1: 
        case 6: 
        case 16: 
        case 17: 
          {  System.err.println("Illegal character: "+yytext());  }
        case 60: break;
        case 3: 
        case 18: 
        case 19: 
        case 20: 
        case 30: 
        case 31: 
        case 38: 
        case 39: 
        case 42: 
        case 43: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 51: 
          {  return sf.newSymbol("Identifier",sym.IDENT,new String(yytext()));  }
        case 61: break;
        case 12: 
          {  return sf.newSymbol("Comma",sym.COMMA);  }
        case 62: break;
        case 15: 
          {  return sf.newSymbol("Equals",sym.EQL);  }
        case 63: break;
        case 8: 
          {  return sf.newSymbol("Semicolon",sym.SEMI);  }
        case 64: break;
        case 32: 
          {  return sf.newSymbol("Input", sym.INPUT);  }
        case 65: break;
        case 2: 
          {  return sf.newSymbol("Integral Number",sym.NUMBER, new Integer(yytext()));  }
        case 66: break;
        case 26: 
          {  return sf.newSymbol("Arrow", sym.ARROW);  }
        case 67: break;
        case 34: 
        case 35: 
        case 41: 
          {    }
        case 68: break;
        case 13: 
          {  return sf.newSymbol("Left Square Bracket",sym.LSB);  }
        case 69: break;
        case 14: 
          {  return sf.newSymbol("Right Square Bracket",sym.RSB);  }
        case 70: break;
        case 10: 
          {  return sf.newSymbol("Left Bracket",sym.LB);  }
        case 71: break;
        case 50: 
          {  return sf.newSymbol("Example",sym.EXAMPLE);  }
        case 72: break;
        case 27: 
        case 33: 
          {  return sf.newSymbol("Float",sym.DOUB, new Double(yytext()));  }
        case 73: break;
        case 29: 
          {  return sf.newSymbol("Float",sym.DOUB, new Double(yytext()));  }
        case 74: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return sf.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
